/* tslint:disable */
/* eslint-disable */
/**
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, driver\'s working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents the start or destination location of a combined transport, e.g. the port.
 * @export
 * @interface CombinedTransportLocation
 */
export interface CombinedTransportLocation {
    /**
     * The latitude value in degrees (WGS84/EPSG:4326) from south to north.
     * @type {number}
     * @memberof CombinedTransportLocation
     */
    latitude: number;
    /**
     * The longitude value in degrees (WGS84/EPSG:4326) from west to east.
     * @type {number}
     * @memberof CombinedTransportLocation
     */
    longitude: number;
}

/**
 * Check if a given object implements the CombinedTransportLocation interface.
 */
export function instanceOfCombinedTransportLocation(value: object): value is CombinedTransportLocation {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function CombinedTransportLocationFromJSON(json: any): CombinedTransportLocation {
    return CombinedTransportLocationFromJSONTyped(json, false);
}

export function CombinedTransportLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CombinedTransportLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function CombinedTransportLocationToJSON(value?: CombinedTransportLocation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

