/* tslint:disable */
/* eslint-disable */
/**
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers\' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.33
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines whether polylines should match the Raster Maps API or the Vector Maps API.
 * 
 * Not only the polyline itself, but also other results and parameters that use the polyline of the route may change slightly, e.g. emission related results and **matchSideOfStreet**.
 * @export
 */
export const PolylineMapType = {
    RASTER: 'RASTER',
    VECTOR: 'VECTOR'
} as const;
export type PolylineMapType = typeof PolylineMapType[keyof typeof PolylineMapType];


export function instanceOfPolylineMapType(value: any): boolean {
    for (const key in PolylineMapType) {
        if (Object.prototype.hasOwnProperty.call(PolylineMapType, key)) {
            if (PolylineMapType[key as keyof typeof PolylineMapType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PolylineMapTypeFromJSON(json: any): PolylineMapType {
    return PolylineMapTypeFromJSONTyped(json, false);
}

export function PolylineMapTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolylineMapType {
    return json as PolylineMapType;
}

export function PolylineMapTypeToJSON(value?: PolylineMapType | null): any {
    return value as any;
}

