/* tslint:disable */
/* eslint-disable */
/**
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers\' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.33
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TollSystem
 */
export interface TollSystem {
    /**
     * The name of the toll system.
     * @type {string}
     * @memberof TollSystem
     */
    name: string;
    /**
     * The name of the toll operator.
     * @type {string}
     * @memberof TollSystem
     */
    operatorName?: string;
    /**
     * The tariff version that has been used.
     * @type {string}
     * @memberof TollSystem
     */
    tariffVersion?: string;
    /**
     * The starting date of the tariff version validity formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339).
     * @type {Date}
     * @memberof TollSystem
     */
    tariffVersionValidFrom?: Date;
}

/**
 * Check if a given object implements the TollSystem interface.
 */
export function instanceOfTollSystem(value: object): value is TollSystem {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TollSystemFromJSON(json: any): TollSystem {
    return TollSystemFromJSONTyped(json, false);
}

export function TollSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TollSystem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'operatorName': json['operatorName'] == null ? undefined : json['operatorName'],
        'tariffVersion': json['tariffVersion'] == null ? undefined : json['tariffVersion'],
        'tariffVersionValidFrom': json['tariffVersionValidFrom'] == null ? undefined : (new Date(json['tariffVersionValidFrom'])),
    };
}

export function TollSystemToJSON(value?: TollSystem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'operatorName': value['operatorName'],
        'tariffVersion': value['tariffVersion'],
        'tariffVersionValidFrom': value['tariffVersionValidFrom'] == null ? undefined : ((value['tariffVersionValidFrom']).toISOString()),
    };
}

