/* tslint:disable */
/* eslint-disable */
/**
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers\' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.33
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The reason why the road or the schedule is violated.
 *  * `PROHIBITED` - The violated road is prohibited in general for the current vehicle such as some roads in city centers, parks, forests and farmland or it is temporarily closed due to construction sites.  
 *  * `DELIVERY_ONLY` - The violated road is prohibited except for delivery vehicles such as factory premises or pedestrian zones. Cars and vans are no delivery vehicles and may produce such violations.  
 *  * `URBAN` - The violated road is prohibited because urban roads are prohibited for the current vehicle. This will not happen for the predefined profiles.  
 *  * `RESIDENTS_ONLY` - The violated road is prohibited because roads flagged as residents only are prohibited for the current vehicle. This will not happen for the predefined profiles.
 *  * `RESTRICTED_ACCESS` - The violated road is prohibited because it has restricted access because a gate or a bollard has to be passed. This will always have **accessType** _PASS_.  
 *  * `VEHICLE_PROPERTY` - The violated road is prohibited for the current vehicle as some vehicle property exceeds a limit such as the weight or height, or the road is prohibited for trucks in general.  
 *  * `COMBINED_TRANSPORT` - The violated road is a boat (ferry) or rail (train or rail shuttle) connection prohibited for the current vehicle.
 *  * `SCHEDULE` - The schedule is violated. The reasons can be found in **scheduleViolationTypes**.
 *  * `BLOCKED_ROAD_BY_INTERSECTION` - The violated road has been blocked through **options[blockIntersectingRoads]**.
 * @export
 */
export const ViolationType = {
    PROHIBITED: 'PROHIBITED',
    DELIVERY_ONLY: 'DELIVERY_ONLY',
    URBAN: 'URBAN',
    RESIDENTS_ONLY: 'RESIDENTS_ONLY',
    RESTRICTED_ACCESS: 'RESTRICTED_ACCESS',
    VEHICLE_PROPERTY: 'VEHICLE_PROPERTY',
    COMBINED_TRANSPORT: 'COMBINED_TRANSPORT',
    SCHEDULE: 'SCHEDULE',
    BLOCKED_ROAD_BY_INTERSECTION: 'BLOCKED_ROAD_BY_INTERSECTION'
} as const;
export type ViolationType = typeof ViolationType[keyof typeof ViolationType];


export function instanceOfViolationType(value: any): boolean {
    for (const key in ViolationType) {
        if (Object.prototype.hasOwnProperty.call(ViolationType, key)) {
            if (ViolationType[key as keyof typeof ViolationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ViolationTypeFromJSON(json: any): ViolationType {
    return ViolationTypeFromJSONTyped(json, false);
}

export function ViolationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViolationType {
    return json as ViolationType;
}

export function ViolationTypeToJSON(value?: ViolationType | null): any {
    return value as any;
}

